---
- hosts: kibana
  remote_user: root

  tasks:
    - name: "下载 kibana-7.9版本"
      shell: |-
        date ;
        Downloads_dir=/usr/local/src
        wget -O $Downloads_dir/kibana-7.9.3-linux-x86_64.tar.gz https://download.cdn.pupuapp.cn/setups/kibana-7.9.3-linux-x86_64.tar.gz > /dev/null
    - name: "解压kibana"
      shell: cd /usr/local/src && tar -xf kibana-7.9.3-linux-x86_64.tar.gz && mv kibana-7.9.3-linux-x86_64 ../kibana-7.9.3
    - name: "复制kibana配置文件"
      template: src=kibana.yml dest=/usr/local/kibana-7.9.3/config/
    - name: "修改目录用户及组"
      shell: chown esuser.esuser -R /usr/local/kibana-7.9.3
    - name: "启动kibana"
      shell: su esuser -c '/usr/local/kibana-7.9.3/bin/kibana & '