version: '2'
services:
    mysql:
        image: docker.io/mysql:5.7
        container_name: stat-mysql
        command: [
            "--server-id=1",
            "--datadir=/var/lib/mysql",
            "--log-bin=/var/lib/mysql/mysql-bin.log",
            "--gtid_mode=ON",
            "--enforce_gtid_consistency=ON"
        ]
        restart: always
        networks:
            app_net:
                ipv4_address: 172.16.1.2
        environment:
            MYSQL_ROOT_PASSWORD: 123
        ports:
            - 3306:3306
        volumes:
            - /mysql/docker_mysql_dir:/var/lib/mysql

    clickhouse:
        image: yandex/clickhouse-server:21.5.6-alpine
        ulimits:
            nofile:
                soft: 262144
                hard: 262144
        container_name: stat-clickhouse
        restart: always
        networks:
            app_net:
                ipv4_address: 172.16.1.3
        ports:
            - 8123:8123
            - 6767:6767
        volumes:
            - /data/docker_clikchouse_dir:/var/lib/clickhouse
            - /etc/clickhouse-server:/etc/clickhouse-server
    
    clickhouse_client:
        image: yandex/clickhouse-server
        container_name: clickhouse_client
        links: 
            - clickhouse
        depends_on:
            - clickhouse
        networks: 
            app_net: 
                ipv4_address: 172.16.1.4

networks:
    app_net:
        driver: bridge
        ipam: 
            driver: default
            config: 
                - subnet: 172.16.1.0/24