---
- hosts: esnode
  remote_user: root
  
  tasks:
    - name: "下载es7.9版本压缩包"
      shell: |-
        date ;
        Downloads_dir=/usr/local/src
        wget -O $Downloads_dir/elasticsearch-7.9.3-linux-x86_64.tar.gz https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.9.3-linux-x86_64.tar.gz >/dev/null
    - name: "解压es压缩包"
      shell: cd /usr/local/src && tar -xf elasticsearch-7.9.3-linux-x86_64.tar.gz && mv elasticsearch-7.9.3 ../elasticsearch-7.9.3
    - name: "复制es配置文件到es服务器"
      template: src=elasticsearch.yml dest=/usr/local/elasticsearch-7.9.3/config/
    - name: "复制修改配置文件脚本"
      template: src=chage.sh dest=/usr/local/src/
    - name: "修改es配置文件"
      shell: sh -x /usr/local/src/chage.sh
    - name: "创建es数据及log目录"
      shell: mkdir -p /data/elasticsearch/{log,data}
    - name: create es user
      user:
        name: esuser
        state: present
    - name: "配置用户及组权限"
      shell: |-
        chown esuser.esuser -R /usr/local/elasticsearch-7.9.3
        chown esuser.esuser -R /data/elasticsearch
    - name: "修改系统配置"
      shell: |-
        echo "vm.max_map_count=262144"  >> /etc/sysctl.conf
        sysctl -p 
        echo "* soft memlock unlimited" >> /etc/security/limits.conf 
        echo "* hard memlock unlimited" >> /etc/security/limits.conf 
    - name: "分别启动es"
      shell: /usr/bin/su - esuser -c '/usr/local/elasticsearch-7.9.3/bin/elasticsearch -p /tmp/elasticsearch_pid -d'